### ISSUE TITLE
SMTP email with Openshift and nodebb-plugin-emailer-local forked from julianlam/nodebb-plugin-emailer-local

### ISSUE THREAD

**Issue by christiangrieger** [ahwayakchih/openshift-nodebb#12]
Hey,

first of all thank your for the nice tutorial. We got all set up well and running without big problems.
We tried to install a plugin called nodebb-plugin-emailer-local on the openshift app but it looks like the smtp mails get blocked from openshift because this errer:

17/2 03:09 [201897] - ^[[33mwarn^[[39m: [emailer.smtp] Unable to send `digest` email to uid 1!!
17/2 03:09 [201897] - ^[[31merror^[[39m: [plugins] filter:email.send,  Greeting never received

Would you be so nice to also explain how to get that plugin running with the openshift setup?

Thank you very much!

**Comment by ahwayakchih** [comment]
Hi,

Are you using 3rd party SMTP server? For example, gmail?

**Comment by christiangrieger** [comment]
No i am using a 3rd party smpt server of my hoster. So is there a chance you can install the plugin i mentioned on top and try to send mails with it on the openshift setup? We really need that this can send mails.

Thank you! :)

**Comment by ahwayakchih** [comment]
I think it is possible, as i did try it (although with GMail account). I should be able to try and test it with another SMTP server tomorrow or over the weekend. So i'll write here then.

But it still will be an SMTP server that's not hosted on OpenShift.

**Comment by nhlpl** [comment]
NodeBB is now using Nodemailer so give it a try and see what happens.
https://blog.nodebb.org/emailers/
http://nodemailer.com

**Comment by christiangrieger** [comment]
I will give it a try thanks.

**Comment by nhlpl** [comment]
https://github.com/NodeBB/NodeBB/issues/4193#issuecomment-186732409
