### ISSUE TITLE
Error at the last step

### ISSUE THREAD

**Issue by Nisthar** [ahwayakchih/openshift-nodebb#13]
`remote: Populating database with default configs, if not already set...
remote: 23/2 10:28 [427673] - error: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
remote:     at errnoException (net.js:905:11)
remote:     at Object.afterConnect [as oncomplete] (net.js:896:19)
remote: CLIENT_RESULT:
remote: CLIENT_RESULT: .-============================================-.
remote: CLIENT_RESULT: .  Setup finished.
remote: CLIENT_RESULT: .
remote: CLIENT_RESULT: .  You can view your NodeBB at:
remote: CLIENT_RESULT: .  https://nodebb-hackthrone.rhcloud.com/
remote: CLIENT_RESULT: ^-============================================-^
remote: CLIENT_RESULT:
remote: Starting NodeJS cartridge
remote: Tue Feb 23 2016 10:28:16 GMT-0500 (EST): Starting application 'nodebb' ...
remote: *** NodeJS supervisor is disabled due to .openshift/markers/use_npm
remote: *** Starting application using: npm start -d
remote: Waiting for application port (8080) become available ...
remote: Application 'nodebb' failed to start (port 8080 not available)
remote: -------------------------
remote: Git Post-Receive Result: failure
remote: Activation status: failure
remote: Activation failed for the following gears:
remote: 56cc73970c1e668f5a00027d (Error activating gear: CLIENT_ERROR: Failed to execute: 'control start' for /var/lib/o
penshift/56cc73970c1e668f5a00027d/nodejs
remote: #<IO:0x00000002543380>
remote: #<IO:0x00000002543308>
remote: )
remote: Deployment completed with status: failure
remote: postreceive failed`

I am not using redis. But its trying to connect to redis when i opened the ./nodebb log. I am using mongodb. Any solution for this?

**Comment by ahwayakchih** [comment]
Hi,

If you selected nodebb to install, then it is strange that nodebb tried to use Redis anyway.
Can you login through SSH and check environment variables?

``` sh
cd nodebb
rhc ssh
printenv | grep OPENSHIFT_REDIS_
printenv | grep MONGO
```

Don't paste then here (as some of them are passwords). Just check if there are variables prefixed with `OPENSHIFT_REDIS_` and if there are variables with either `OPENSHIFT_MONGODB_` or `MONGOLAB` prefix.

**Comment by nhlpl** [comment]
It's working for me and was restarted when I visited it.
https://nodebb-hackthrone.rhcloud.com

**Comment by Nisthar** [comment]
@nhlpl @ahwayakchih  Yes. I think i missed adding mongodb cartiridge to the account. I added the cartirdge and had to manually run the ./nodebb setup. 

It seems working now.

**Comment by ahwayakchih** [comment]
Great :).
