### ISSUE TITLE
Cant get social media registering to work

### ISSUE THREAD

**Issue by Nisthar** [ahwayakchih/openshift-nodebb#14]
Hi,

I added the alias hackthrone.com to my openshift app and installed the facebook-sso plugin. But when i tried to access it from hackthrone.com. But its redirecting to this url https://www.facebook.com/dialog/oauth?response_type=code&redirect_uri=https%3A%2F%2Fnodebb-hackthrone.rhcloud.com%2Fauth%2Ffacebook%2Fcallback&scope=email%2C%20user_friends&client_id=1708298502716118 

and i am getting the error.To be clear the redirect_uri in the link is https://nodebb-hackthrone.rhcloud.com. I want the redirect_uri to be hackthrone.com.Any solution to this issue?

**Comment by nhlpl** [comment]
I guess you want to configure a custom domain name.
https://github.com/ahwayakchih/openshift-nodebb#custom-domain-name

And more in OpenShift documentation:
https://developers.openshift.com/en/managing-domains-ssl.html#_step_1_configure_a_domain_alias_in_the_openshift_web_console_or_command_line_rhc

**Comment by Nisthar** [comment]
@nhlpl I tried it with my previous official setup. It didn't worked. i'll try it again with my new setup

**Comment by nhlpl** [comment]
You have to point your domain to OpenShift clound.

Sign-in to your domain management and change.
name: hackthrone.com
record type: A
refresh time (TTL, time-to-live): 1 hour OR 3600 seconds
value: nodebb-hackthrone.rhcloud.com

**Comment by Nisthar** [comment]
@nhlpl Yes. I am using cloudflare and cloudflare only allows ip address in A records. I tried adding the ip address of thehost. But it just redirects to hackthrone.com/app. I am not sure if its the case with my new setup though. I'll test it out tomorrow and post the result :+1:

**Comment by Nisthar** [comment]
@nhlpl I tried setting the env variable OPENSHIFT_APP_DNS_ALIAS. But when it opens the facebook, Its always passing redirect_uri as the openshift url instead of my domain.

**Comment by Nisthar** [comment]
@nhlpl Is there any way i can disable the openshift url permenantly and use my domain with the app?

**Comment by Nisthar** [comment]
@nhlpl  Ok. I tried editing the config.json file and set the url option to http://mydomain.com and restarted the app. But now. When i click on the facebook login button its passing the redirect_uri as https://mydomain.com.

**Comment by ahwayakchih** [comment]
@Nisthar Setting up OPENSHIFT_APP_DNS_ALIAS variable should have work and make config.url changed automatically. You just had to restart application after setting it.

As for https, you can disable it by editing openshift-app.js locally and changing line 35: https://github.com/ahwayakchih/openshift-nodebb/blob/master/openshift-app.js#L35 so there's "http" instead of "https". After change, use `git commit -a -m "enforce insecure website"` command and `git push origin master`.

**Comment by Nisthar** [comment]
@ahwayakchih I am getting a new error now. 

`24/2 01:21 [322750] - info: NodeBB Ready
[cluster] Child Process (322750) has exited (code: 0, signal: null)
24/2 01:21 [322750] - info: Enabling 'trust proxy'
24/2 01:21 [322750] - error:  Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickDomainCallback (node.js:486:13)
24/2 01:21 [322750] - error: NodeBB address in use, exiting...
`
I thought its because another process is using 8080 port. Stopped all application. Reran. Changed config.url to http://nodebb-hackthrone.rhcloud.com. Changed the openshift-app.js to default(with https)
Still the same error.
The git push was success and shows the app is running. But i am getting this error when i do `./nodebb log`
Can you think of possible causes?
(Any way can i edit the openshift-app.js directly in the server? I can't find the file in my repo)

**Comment by ahwayakchih** [comment]
`openshift-app.js` is changed to `app.js` after deployment. So, if you want to edit "live" version of file, edit, `app.js`.

**Comment by Nisthar** [comment]
@ahwayakchih Anyway i'll try with a new installation now.

**Comment by Nisthar** [comment]
@ahwayakchih Ok. The `Error: listen EADDRINUSE at errnoException` happend again when i ran `rhc set-env OPENSHIFT_APP_DNS_ALIAS=hackthrone.com -a nodebb` (on new installation)

**Comment by nhlpl** [comment]
Could you please confirm it's a new install and you've followed a guide? When you're running manual setup you'll get wrong and changable IP address and port number in your config.json.

OpenShift cloud uses Environment Variables.

```
var ipaddress = process.env.OPENSHIFT_NODEJS_IP || "127.0.0.1";
var port      = process.env.OPENSHIFT_NODEJS_PORT || 8080;
```

Documentation:
https://developers.openshift.com/en/managing-environment-variables.html#informational-variables

**Comment by Nisthar** [comment]
@nhlpl No. I did followed this guide.

**Comment by nhlpl** [comment]
Please check used ports with:

```
netstat -tulpn
netstat -tulpn | grep :$OPENSHIFT_NODEJS_PORT
```

**Comment by Nisthar** [comment]
@nhlpl Its saying permission denied. I am new to openshift. I thought they give root permission. But it looks like they dont

**Comment by nhlpl** [comment]
`./nodebb stop` and try again with your commands related to domain name.

or try to use their GUI:
https://blog.openshift.com/domain-names-and-ssl-in-the-openshift-web-console/

**Comment by Nisthar** [comment]
@nhlpl Yes. I think the problem is with openshift. I had to stop the nodebb app before restarting openshift app. I managed to fix it with a new installation. Dont know the exact cause though. Thanks :+1:

**Comment by nhlpl** [comment]
You have to actually change dir (open folder) for some commands to execute. Usually it should be your app repo /nodebb.

Could you please confirm how to enable custom domain so we can update a guide?

**Comment by Nisthar** [comment]
@nhlpl I did ran the commands in the repo folder. I think this guide has no errors. First, I changed the config.url to my http://www.hackthrone.com. Then i stopped the nodebb application and ran the command `rhc set-env OPENSHIFT_APP_DNS_ALIAS=www.hackthrone.com -a nodebb` and restarted my openshift app. Then i just need to start my nodebb application and it worked :+1: 

Sorry for my bad english.

**Comment by Nisthar** [comment]
The difference was i didn't stopped the nodebb application for my previous tries.

**Comment by nhlpl** [comment]
Thanks a lot for your confirmation.

@ahwayakchih we need to add a note about stopping NodeBB.

Solved.

**Comment by ahwayakchih** [comment]
@nhlpl restarting is needed when someone manually changes files directly on OpenShift server. editing config.url manually should not be needed - that is what setting up `OPENSHIFT_APP_DNS_ALIAS` is for. I'll have to test installation and see if maybe something changed and overriding url through this environmental variable stopped working.
restarting is mentioned as step 3 for using custom domain. Do you think we should mention it elsewhere too?

**Comment by Nisthar** [comment]
@ahwayakchih I did restarted for my previous tries. But i had forgotten to stop the nodebb app. I think that was the issue with `eaddrinuse` error.

**Comment by ahwayakchih** [comment]
@Nisthar hmm... i was sure that `rhc app restart nodebb` stops and starts application again, but maybe that's not the case. Thanks for the info, i'll look into that.

**Comment by Nisthar** [comment]
I ran the commands to update my nodebb version. But forgot to stop the nodebb application. Now getting the same error. The funny thing is that i am able to access my app even though theres error. But its still in 0.9.3.

I think the two versions are running in parallel and the 0.9.4 version is outputting the error `EAADDRINUSE`. 

Sorry for bad english.

**Comment by ahwayakchih** [comment]
Have you by any chance enabled hot_plug deployments? That would explain, why application is not restarted automatically.

Try to stop it now, and restart - maybe it will work, since files should be updated by now.

**Comment by Nisthar** [comment]
@ahwayakchih I already tried stopping nodebb app and restarting the openshift app. But its still the same.

**Comment by Nisthar** [comment]
I'll try it again now to confirm.

**Comment by Nisthar** [comment]
Yes. Its showing the nodebb is already stopped. But i can access it. I don't know how its working.

The only thing i can think of is that the previous version 0.9.3 (that i forgot to stop) is already running. Not sure though.

**Comment by ahwayakchih** [comment]
How do you stop nodebb? Using `rhc stop` or calling `nodebb stop` "directly" (through SSH)?

**Comment by Nisthar** [comment]
Calling nodebb stop directly through ssh (from git bash)
Do i need to run `rhc stop` ?

**Comment by ahwayakchih** [comment]
Try ~~`rhc restart`~~ `rhc app restart nodebb` instead.

**Comment by Nisthar** [comment]
Ok. Still the same error. But was able to access the nodebb app.
 I stopped openshift app using `rhc app stop nodebb` and tried to access the app, the app returned 503 as expected. Then i started the openshift app and now the nodebb app completely stopped, i think. returning 503 error.

**Comment by ahwayakchih** [comment]
Try to wait a minute or so - it takes a bit of time before various software between you and application updates caches. Browsers also can insist on using cached value (Chrome sometimes needs restart here, because sometime regular cache clear doesn't seem to work for 503).

**Comment by Nisthar** [comment]
Ok. Still not working. You can access it here http://www.hackthrone.com

**Comment by ahwayakchih** [comment]
Indeed, does not work from here too :(. Did `rhc app start nodebb` return any errors?

**Comment by Nisthar** [comment]
No. It was successful. 
`RESULT:
nodebb started`
I also ran `rhc tail -a nodebb` for log. It is also good.

**Comment by ahwayakchih** [comment]
Can you check through SSH if any nodebb is running? Maybe check running processes.

**Comment by Nisthar** [comment]
ran `./nodebb stop`. Returned "NodeBB is already stopped.".

**Comment by ahwayakchih** [comment]
`nodebb stop` depends on the PID file. If, for some reason, that file was removed while nodebb was still running, then it will think that no nodebb is running.

In this case, however, we get 503, so we may assume no nodebb is running.

I wonder why it was not started after `rhc app restart nodebb`. Can you try `rhc app start nodebb` now? And if it tells you, it is already running, try `rhc app stop nodebb` first.

**Comment by Nisthar** [comment]
@ahwayakchih I think i tried both commands.

When i run `rhc app restart nodebb`. The 0.9.3 was running even if the nodebb thrown error.
But when i ran `rhc app stop nodebb` and `rhc app start nodebb`. It stopped working and still getting `EADDRINUSE` error.

**Comment by ahwayakchih** [comment]
How did you update nodebb? Did you follow: https://github.com/ahwayakchih/openshift-nodebb#1-pull-changes ? Did you call `git` commands locally, or through SSH on OpenShift's machine? Because git commands should be run locally.

**Comment by Nisthar** [comment]
I tried it locally. I followed this guide.

**Comment by ahwayakchih** [comment]
I'm running installation process now to see if something has changed in 0.9.x branch that breaks this guide. I will let you know how it went.

**Comment by Nisthar** [comment]
Thanks.

**Comment by ahwayakchih** [comment]
OK, looks like stopping nodebb... stopped working. I installed and added custom domain without a problem. But after adding plugin and pushing changes i got:

```
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 325 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Stopping NodeJS cartridge
remote: Warning: Application 'nodebb' is currently not running.
remote: Thu Feb 25 2016 09:07:21 GMT-0500 (EST): Stopping application 'nodebb' ...
remote: kill 46844: No such process
remote: Thu Feb 25 2016 09:07:21 GMT-0500 (EST): Stopped Node application 'nodebb'
```

Last year they removed `npm stop` command support, so maybe that's related. I'll have to test it more before finding out what is the problem. Unfortunately i will not be able to work on this today.

**Comment by Nisthar** [comment]
Ok np. I'll create a new app from scratch anyway.

**Comment by ahwayakchih** [comment]
@Nisthar i think it is ok now. I added some action_hook scripts to make sure that nodebb is stopped before `rhc app restart` and/or applying changes pushed to repo. NodeJS control script still outputs false information about application not running... but it can be ignored for now.

**Comment by Nisthar** [comment]
@ahwayakchih Thanks. But i am unfortunately having many issues with openshift hosting. Its happening one after the other. Now i am having  `proxy 'express' has no server available!`. Reply if you have any understanding of the issue. I know its happening because there is nothing acting as a server. But my server is already running successful. It happend when i tried to stop nodebb app and change the cloudflare nameserver to my default godaddy nameserver without stopping the openshift app. I think i should contact openshift support.

**Comment by nhlpl** [comment]
We are not serving OpenShift support here. If you want to get help contact OpenShift support or read documentation. Alternatively look for solution on the internet.

If you still want to ask please always write all the details. What, how and why. We are not reading in your mind. Give us more information (plugins, themes, steps, how to reproduce).

**Comment by Nisthar** [comment]
@nhlpl Yes. I know. I just posted here to know if anyone of you guys had the same issue, it may help me solve it fast. yes, I'll try to resolve it myself or will contact openshift support.

**Comment by theunknownartisthour** [comment]
Heyo! If you're trying to install nodebb on openshift take a quick look here.
http://nodebb-francais.readthedocs.org/projects/nodebb/en/latest/installing/cloud/openshift.html

If you're confused...no worries...I wrote that page...nodebb is a pain to get working. But I'd be glad to help, I took down my own forum a while ago because it was pretty outdated. I'd be glad to help setup yours.

**Comment by ahwayakchih** [comment]
@Nisthar problem was that NodeBB process was not closed when restarting. That is why you were getting errors about port number in use, etc... With latest changes i fixed that, but you will have to kill NodeBB or install whole thing a new. To kill it, you can check list of processes. Log into SSH, and then:

``` sh
ps -aux | grep node
```

That should list nodejs processes. You can kill the first one and others should go too. Just take it's ID number from the list and then:

``` sh
kill 123456
```

(where 123456 is that process ID number).

It should start working after that.

**Comment by Nisthar** [comment]
@ahwayakchih Ok.

**Comment by ahwayakchih** [comment]
@theunknownartisthour Thanks for your instruction :). But i think it's not that good to hardcode things like port number into config.json - OpenShift does not guarantee it will stay the same between restarts. Also files uploaded to NodeBB may vanish if they're not in persistent data directory nor in git repo.

**Comment by ahwayakchih** [comment]
@Nisthar forgot to mention - update your files, following "updates" process (https://github.com/ahwayakchih/openshift-nodebb#updates), after you kill NodeBB.

**Comment by Nisthar** [comment]
@ahwayakchih  Hi, I just tried a new installation. I think theres some issue after your recent commit. I am getting this error when i git push:

`remote: Activating deployment
remote: HAProxy already running
remote: CLIENT_RESULT: HAProxy instance is started
remote: Configuring NodeBB 0.9.4 for OpenShift
remote: Patching /var/lib/openshift/56d268a97628e17307000154/nodejs/configuration/node.env
remote: Overriding app.js
remote: Pointing uploads directory to [OPENSHIFT_DATA_DIR]/nodebb/public-uploads
remote: Pointing logs directory to [OPENSHIFT_DATA_DIR]/nodebb/logs
remote: Pointing config.json to [OPENSHIFT_DATA_DIR]/nodebb/config.json
remote: Running setup
remote: [Error: Wrong data returned]
remote:
remote: /var/lib/openshift/56d268a97628e17307000154/app-root/runtime/repo/node_modules/nconf/lib/nconf/stores/file.js:16
0
remote:     throw new Error("Error parsing your configuration file: [" + this.file + '
remote:           ^
remote: Error: Error parsing your configuration file: [/var/lib/openshift/56d268a97628e17307000154/app-root/runtime/repo
/config.json]: Unexpected end of input
remote:     at File.loadSync (/var/lib/openshift/56d268a97628e17307000154/app-root/runtime/repo/node_modules/nconf/lib/n
conf/stores/file.js:160:11)
remote:     at Provider.add (/var/lib/openshift/56d268a97628e17307000154/app-root/runtime/repo/node_modules/nconf/lib/nc
onf/provider.js:137:23)
remote:     at Provider.file (/var/lib/openshift/56d268a97628e17307000154/app-root/runtime/repo/node_modules/nconf/lib/n
conf/provider.js:63:15)
remote:     at loadConfig (/var/lib/openshift/56d268a97628e17307000154/app-root/runtime/repo/_app.js:88:8)
remote:     at Object.<anonymous> (/var/lib/openshift/56d268a97628e17307000154/app-root/runtime/repo/_app.js:58:1)
remote:     at Module._compile (module.js:456:26)
remote:     at Object.Module._extensions..js (module.js:474:10)
remote:     at Module.load (module.js:356:32)
remote:     at Function.Module._load (module.js:312:12)
remote:     at Module.require (module.js:364:17)
remote: CLIENT_RESULT:
remote: CLIENT_RESULT: .-============================================-.
remote: CLIENT_RESULT: .  Setup finished.
remote: CLIENT_RESULT: .
remote: CLIENT_RESULT: .  You can view your NodeBB at:
remote: CLIENT_RESULT: .  http://nodebb-htforum.rhcloud.com/
remote: CLIENT_RESULT: ^-============================================-^
remote: CLIENT_RESULT:
remote: Starting NodeJS cartridge
remote: Sat Feb 27 2016 23:01:39 GMT-0500 (EST): Starting application 'nodebb' ...
remote: *** NodeJS supervisor is disabled due to .openshift/markers/use_npm
remote: *** Starting application using: npm start -d
remote: Waiting for application port (8080) become available ...
remote: Application 'nodebb' failed to start (port 8080 not available)
remote: -------------------------
remote: Git Post-Receive Result: failure
remote: Activation status: failure
remote: Activation failed for the following gears:
remote: 56d268a97628e17307000154 (Error activating gear: CLIENT_ERROR: Failed to execute: 'control start' for /var/lib/o
penshift/56d268a97628e17307000154/nodejs
remote: #<IO:0x00000001ee5380>
remote: #<IO:0x00000001ee5308>
remote: )
remote: Deployment completed with status: failure
remote: postreceive failed
To ssh://56d268a97628e17307000154@nodebb-htforum.rhcloud.com/~/git/nodebb.git/
   8b21dc2..836e45b  master -> master`

**Comment by theunknownartisthour** [comment]
@ahwayakchih I wrote that guide a long time ago, well before I learned that the environment variables were accessible through node js and that you could add them into config.js. But for the most part openshift has dedicated ports for certain services so it wasn't that bad of a start.

I did a test install from the instructions and I'm also getting the above error. I'll see what I can do to help.
I'll test the other variations in a bit, but I currently tried to do the install with redis and nodejs 0.10 , see if any of the combinations do work right off the bat.

**Comment by nhlpl** [comment]
@theunknownartisthour 

Could you please update NodeBB Documentation and add a link to this guide on the bottom of the page?
https://github.com/NodeBB/nodebb-english/pulls

Thank You!

**Comment by theunknownartisthour** [comment]
@nhlpl I certainly will go back and do that once we resolve these errors, no problem.

It appears the error above is because config.json is created, but nothing is stored inside, so loadConfig() fails. Probably could be resolved if nconf was used to overwrite the file from openshift-app.js

Or it may also be solved by not creating an empty config.json in the deploy script.

**Comment by ahwayakchih** [comment]
@theunknownartisthour yep, thanks. I'm working on a lot of changes, and will include a fix for that too.

**Comment by ahwayakchih** [comment]
@theunknownartisthour it should be fixed now.

**Comment by theunknownartisthour** [comment]
@ahwayakchih I'll do another test run then, let you guys know what happens.

**Comment by ahwayakchih** [comment]
Thanks

**Comment by Nisthar** [comment]
@ahwayakchih If i may ask, What env variable should i set to my app so that it uses my alias for websocket connection? I tried setting OPENSHIFT_NODEBB_WS_USE_APP_DNS=true. But it doesn't worked and its still connecting to wss://nodebb-xxxxx.rhcloud.com.

**Comment by ahwayakchih** [comment]
@Nisthar that was changed - setting different domains for http and ws did not really work, as reported in #7 :(. That's why i removed it for now and added automatic checking if SSL is working. I can bring it back if needed.

I updated README for it: https://github.com/ahwayakchih/openshift-nodebb#custom-domain-name

**Comment by Nisthar** [comment]
@ahwayakchih Ok. I think i got it.

**Comment by Nisthar** [comment]
@ahwayakchih Actually, I was trying to set the http and ws to the same domain. I edited the app.js and hardcoded my domain `config['socket.io'].address = 'ws://hackthrone.com:8000';`. My domain is from godaddy. I see it can't connect to ws://hackthrone.com:8000. But it can connect to 'ws://nodebb-htforum.rhcloud.com'.

**Comment by Nisthar** [comment]
Connecting to 'ws://nodebb-htforum.rhcloud.com' is useless as its a different domain and if i access my app through hackthrone.com, I can't edit or create new topic as the sessions are on a different domain.

**Comment by ahwayakchih** [comment]
@Nisthar do you access your website through your custom domain name? Did you add custom domain name as alias to nodebb application (`rhc alias add nodebb example.com`)? Do you use CloudFlare (it does not support SSL websockets) or anything similar?

**UPDATE:** Not sure why you hardcoded domain name for websocket. If you did setup custom domain name, openshift-app.js should be using the same domain name for both http(s) and ws(s) by default.

**Comment by Nisthar** [comment]
@ahwayakchih Yes. I ran `rhc set env OPENSHIFT_APP_DNS_ALIAS=hackthrone -a nodebb`. But not `rhc alias add nodebb hackthrone.com` as i already added the alias in openshift without using the command. I was using cloudflare. But since they dont support websocket. I changed my domain nameservers to godaddy default and updated the www CNAME to `nodebb-htforum.rhcloud.com` . Even if i hardcoded it or not, the ws connection to ws://hackthrone.com:8000 is not successful. I don't know why.

**Comment by Nisthar** [comment]
@ahwayakchih My issue is i can't update or create new topic since the websocket is connected to wss://nodebb-htforum.rhcloud.com:8443 rather than ws://hackthrone.com:8000.

**Comment by ahwayakchih** [comment]
@Nisthar right now your site is offline, so i can't check it, but when i first tried through HTTPS i got error about incorrect SSL certificate (because it is a default certificate for *.rhcloud, and not valid certificate for your domain). Since openshift-app.js checks validity of SSL, it sees rejected connection, and sets its internal `USE_SSL` variable to false. Which in turn makes it configure NodeBB to be used without SSL. If you keep accessing the site through HTTPS, browser will block connection to insecure websocket address.
Try accessing site through HTTP, without hardcoding anything.

**Comment by Nisthar** [comment]
@ahwayakchih I am accessing the site without HTTP. Also i hardcoded because if i dont, Its using the ws://nodebb-htforum.rhcloud:8443 for the websocket connection. The connection will be successful. But since i'll be accessing the site through http://www.hackthrone.com. I can't update or create new topic. Its happening because of the ws connection to a different domain. if I can connect to ws://hackthrone.com:8000 , the issue may be resolved. But i dont know but the connections are not successful to ws://hackthrone.com:8000.

**Comment by ahwayakchih** [comment]
@Nisthar  OK, let's try this test:

``` sh
rhc ssh nodebb
cd app-root/repo
nano app.js
```

Scroll down to, or find line with:

``` js
nconf.overrides(config);
```

Change it to:

``` js
console.log('OpenShift NodeBB config overrides:', config);
nconf.overrides(config);
```

Then restart (still staying logged in to SSH):

``` sh
./nodebb stop && ./nodebb start && ./nodebb log
```

Check what config overrides it will output. It should be something along the line of:

```
OpenShift NodeBB config overrides { port: '8080',
  bind_address: '127.11.60.1',
  url: 'http://www.hackthrone.com',
  'socket.io': { address: 'ws://www.hackthrone.com:8000' },
```

**Comment by Nisthar** [comment]
@ahwayakchih Ok. I'll try it now.

**Comment by Nisthar** [comment]
@ahwayakchih Oh, It looks like i am using old version of this repo. Let me update it.

**Comment by ahwayakchih** [comment]
@Nisthar OK, let us know how it went :).

**Comment by Nisthar** [comment]
@ahwayakchih Idk if its an error in my server or not. But after updating, It broke. I ran `git pull --no-edit -s recursive -X theirs openshift master` to update and `git push origin master`. But it broke here:
`remote: Pointing uploads directory to /var/lib/openshift/56d3d2e189f5cfad110001a1/app-root/data/nodebb/public-uploads
remote: Pointing logs directory to /var/lib/openshift/56d3d2e189f5cfad110001a1/app-root/data/nodebb/logs
remote: Pointing config.json to /var/lib/openshift/56d3d2e189f5cfad110001a1/app-root/data/nodebb/config.json
remote: Running setup
remote:
remote: events.js:72
remote:         throw er; // Unhandled 'error' event
remote:               ^
remote: Error: listen EADDRINUSE
remote:     at errnoException (net.js:905:11)
remote:     at Server._listen2 (net.js:1043:14)
remote:     at listen (net.js:1065:10)
remote:     at net.js:1147:9
remote:     at dns.js:72:18
remote:     at process._tickCallback (node.js:442:13)
remote:     at Function.Module.runMain (module.js:499:11)
remote:     at startup (node.js:119:16)
remote:     at node.js:929:3
remote: CLIENT_RESULT:
remote: CLIENT_RESULT: .-============================================-.
remote: CLIENT_RESULT: .  Setup failed.
remote: CLIENT_RESULT: .
remote: CLIENT_RESULT: .  There was a problem completing NodeBB setup.
remote: CLIENT_RESULT: .
remote: CLIENT_RESULT: .  Check logfile for more information:
remote: CLIENT_RESULT: .  logs/openshift-nodebb-setup.log
remote: CLIENT_RESULT: ^-============================================-^`

**Comment by nhlpl** [comment]
Please test it in a newly created gear and do not install any additional software like HAProxy.

**Comment by ahwayakchih** [comment]
@Nisthar looks like previous installation was still running? Try this list of commands:

``` sh
rhc ssh nodebb
cd app-root/repo
./nodebb stop
sleep 1
pkill -u $OPENSHIFT_APP_UUID -x node -o
lsof
```

Check if output after lsof still contains node, if it does, kill its ID too.

Then, still through SSH:

``` sh
ctl_app deploy HEAD
```

**Comment by Nisthar** [comment]
@ahwayakchih The last error has gone. But got a error after 
`*** NodeJS supervisor is disabled due to .openshift/markers/use_npm
*** Starting application using: npm start -d
Waiting for application port (8080) become available ...
Found 127.13.17.129:8080 listening port
Application 'nodebb' failed to start 1
Error: Timeout
CLIENT_RESULT:
CLIENT_RESULT: .-============================================-.
CLIENT_RESULT: .  NodeBB failed to start for some reason.
CLIENT_RESULT: .
CLIENT_RESULT: .  Check logfile for more information:
CLIENT_RESULT: .  logs/output.log
CLIENT_RESULT: ^-============================================-^
`
But its running without an error when i checked it.

**Comment by Nisthar** [comment]
Just to be clear: the websocket is not working. Do you have any idea to make websocket working with godaddy domain?

**Comment by nhlpl** [comment]
Domain propagation can take up to 24 hours. Please read how it works.

**Comment by ahwayakchih** [comment]
@Nisthar looks like there was still something else listening on port 8080 there? Did you make sure that no node was running before deploying again?

As for websocket - i tested my domain today and it works just fine, but only on HTTP (no SSL). All i did was edit domain name entry, to set CNAME subomain to point to nodebb-example.rhcloud.com domain, and followed steps from the guide to add domain to OpenShift application and NodeBB.
Make sure, that there is only one domain alias added to application (you can check that in OpenShift webconsole).
I don't know how you did set up domain on godaddy's side of things.

**Comment by Nisthar** [comment]
@ahwayakchih I set the www CNAME to nodebb-xxxx.rhcloud.com and ran the command `rhc env set OPENSHIFT_APP_DNS_ALIAS=hackthrone.com -a nodebb` and set the INSECURE env variable to true. But it didn't worked. Let me try it again.

**Comment by ahwayakchih** [comment]
@Nisthar what INSECURE variable? what error does the browser show?

**Comment by ahwayakchih** [comment]
@Nisthar one more thing: how long did the deploy wait between: `Found 127.13.17.129:8080 listening port` and `Error: Timeout`? Because timeout is currently set to 2 minutes, and OpenShift can sometimes be very slow on deployment process, so maybe 3 or 5 minutes of max timeout would be better?

**Comment by Nisthar** [comment]
@ahwayakchih I mean this command `rhc set-env OPENSHIFT_NODEBB_WS_USE_INSECURE=true -a nodebb`. It shouldn't have took more than 2 minutes, I think

**Comment by Nisthar** [comment]
This is the log from chrome debug tool on websocket connection error:
`Request URL:wss://www.hackthrone.com:8443/socket.io/?EIO=3&transport=websocket&sid=wqZ6e1o8WixB5FWTAAAI
Request Method:GET
Status Code:400 Bad Request`

Also, In my case the polling works only if i enable https version. But if i run the command `rhc set-env OPENSHIFT_NODEBB_WS_USE_INSECURE=true -a nodebb`. Both will no longer work.

**Comment by ahwayakchih** [comment]
@Nisthar sorry, but it seems that you keep using old code and trying to access site through SSL.

Setting or unsetting `OPENSHIFT_NODEBB_WS_USE_INSECURE` should not make ANY difference, since it is not used by openshift-nodebb anymore.

Debug from Chrome shows that it tries to access websockets through SSL, which will not work without correct and valid SSL certificate.

**Comment by Nisthar** [comment]
@ahwayakchih Sorry, I was using my test account which is running old version of this repo(thought it will not make any difference). I'll switch to the account running latest version.

**Comment by Nisthar** [comment]
@ahwayakchih BTW were you trying with godaddy? Because i think godaddy doesn't support CNAME flattening. I dont have full info about it. But its required to work with openshift app.

I set up the CNAME in godaddy. But when i access http://www.hackthrone.com ,its redirecting me to https://www.hackthrone.com/app.

**Comment by Nisthar** [comment]
Ok. It might be due to me adding the domain name in openshift as hackthrone.com instead of www.hackthrone.com

**Comment by Nisthar** [comment]
Ok. I can access the site after adding domain name as www.hackthrone.com

**Comment by ahwayakchih** [comment]
@Nisthar alias should be exactly the same as the one entered in CNAME. Also, do not use "hackthrone.com" or you will have other troubles later (like no e-mails received). It is better to use subdomain, e.g., nodebb.hackthrone.com :)

> BTW were you trying with godaddy?

No, i use DNS provider in Poland.

**Comment by Nisthar** [comment]
Ok. I'll use www.hackthrone.com if its okay.

**Comment by Nisthar** [comment]
Ok. The websocket is working fine now. I had to run `rhc env set OPENSHIFT_APP_DNS_ALIAS=www.hackthrone.com -a nodebb` and restart the openshift app. Thanks :+1:

**Comment by ahwayakchih** [comment]
Great!

**Comment by ahwayakchih** [comment]
@Nisthar Is FB login working OK now? Can we close this issue?

**Comment by Nisthar** [comment]
@ahwayakchih Yes. Its working now.

**Comment by ahwayakchih** [comment]
Thanks.
