### ISSUE TITLE
Error parsing your configuration file

### ISSUE THREAD

**Issue by Nisthar** [ahwayakchih/openshift-nodebb#15]
This is the error i am getting. There was no error before. Might be due to the recent changes in the code.
Log during git push:
`remote: [Error: Wrong data returned]
remote:
remote: /var/lib/openshift/56d2e54f0c1e66d9920000bc/app-root/runtime/repo/node_modules/nconf/lib/nconf/stores/file.js:16
0
remote:     throw new Error("Error parsing your configuration file: [" + this.file + '
remote:           ^
remote: Error: Error parsing your configuration file: [/var/lib/openshift/56d2e54f0c1e66d9920000bc/app-root/runtime/repo
/config.json]: Unexpected end of input
remote:     at File.loadSync (/var/lib/openshift/56d2e54f0c1e66d9920000bc/app-root/runtime/repo/node_modules/nconf/lib/n
conf/stores/file.js:160:11)
remote:     at Provider.add (/var/lib/openshift/56d2e54f0c1e66d9920000bc/app-root/runtime/repo/node_modules/nconf/lib/nc
onf/provider.js:137:23)
remote:     at Provider.file (/var/lib/openshift/56d2e54f0c1e66d9920000bc/app-root/runtime/repo/node_modules/nconf/lib/n
conf/provider.js:63:15)
remote:     at loadConfig (/var/lib/openshift/56d2e54f0c1e66d9920000bc/app-root/runtime/repo/_app.js:88:8)
remote:     at Object.<anonymous> (/var/lib/openshift/56d2e54f0c1e66d9920000bc/app-root/runtime/repo/_app.js:58:1)
remote:     at Module._compile (module.js:456:26)
remote:     at Object.Module._extensions..js (module.js:474:10)
remote:     at Module.load (module.js:356:32)
remote:     at Function.Module._load (module.js:312:12)
remote:     at Module.require (module.js:364:17)
remote: CLIENT_RESULT:
remote: CLIENT_RESULT: .-============================================-.
remote: CLIENT_RESULT: .  Setup finished.
remote: CLIENT_RESULT: .
remote: CLIENT_RESULT: .  You can view your NodeBB at:
remote: CLIENT_RESULT: .  http://nodebb-htforum.rhcloud.com/
remote: CLIENT_RESULT: ^-============================================-^
remote: CLIENT_RESULT:
remote: Starting NodeJS cartridge
remote: Sun Feb 28 2016 08:01:28 GMT-0500 (EST): Starting application 'nodebb' ...
remote: *** NodeJS supervisor is disabled due to .openshift/markers/use_npm
remote: *** Starting application using: npm start -d
remote: Waiting for application port (8080) become available ...
remote: Application 'nodebb' failed to start (port 8080 not available)
remote: -------------------------
remote: Git Post-Receive Result: failure
remote: Activation status: failure
remote: Activation failed for the following gears:
remote: 56d2e54f0c1e66d9920000bc (Error activating gear: CLIENT_ERROR: Failed to execute: 'control start' for /var/lib/o
penshift/56d2e54f0c1e66d9920000bc/nodejs
remote: #<IO:0x0000000107f390>
remote: #<IO:0x0000000107f318>
remote: )
remote: Deployment completed with status: failure
remote: postreceive failed
To ssh://56d2e54f0c1e66d9920000bc@nodebb-htforum.rhcloud.com/~/git/nodebb.git/`

**Comment by nhlpl** [comment]
theunknownartisthour has found a bug. Please wait for a hotfix.
https://github.com/ahwayakchih/openshift-nodebb/issues/14#issuecomment-189834845

**Comment by Nisthar** [comment]
@nhlpl Ok.

**Comment by ahwayakchih** [comment]
Thanks for report @Nisthar 

It should be fixed now. I've run 3 fresh installs (0.9.x with Redis, 0.9.x with MongoDB, 0.8.x with Redis) and all worked ok (installed, NodeBB started ok) and then updated each of them (updated OK).

Sorry it took so long, but i wanted to add waiting for NodeBB to start before printing URL and making sure NodeBB is not running when not needed :).

**Comment by Nisthar** [comment]
@ahwayakchih Thanks. Will check it now.

**Comment by ahwayakchih** [comment]
Thanks

**Comment by ahwayakchih** [comment]
Fixed: https://github.com/ahwayakchih/openshift-nodebb/issues/14#issuecomment-190281002

**Comment by theunknownartisthour** [comment]
Just confirmed the application runs on the default host, if I get it working with a cname I'll be updating the old docs.

Edit: Just confirmed aliasing works properly, next I'll test ssl.

Edit2: Sent pull request on nodebb's docs see [here](https://github.com/NodeBB/nodebb-english/pull/79)

**Comment by ahwayakchih** [comment]
Thanks
