### ISSUE TITLE
No config.json file

### ISSUE THREAD

**Issue by nsjohannes** [ahwayakchih/openshift-nodebb#20]
Hi. I've just recently installed NodeBB with this guide. I also added an alias to my Openshift Domain. However, the forum is still using the namespace-domain.rhcloud.com url so I need to change it to the alias I set. The problem is there's no config.json file so I can't change the URL of the NodeBB installation?

**Comment by Nisthar** [comment]
@nsjohannes Which version of nodebb are you using? 

I had the same issue. I think i solved it using the config.json.

**Comment by nsjohannes** [comment]
@Nisthar The latest version, as far as I know. I don't have config.json

**Comment by Nisthar** [comment]
@nsjohannes I think this package does not support latest version. It only support versions less than 1.0.0

**Comment by nsjohannes** [comment]
@Nisthar I checked in my Admin CP. I'm using 0.9.4, not the latest version

**Comment by ahwayakchih** [comment]
@nsjohannes please check if this command outputs config data (after you log into OpenShift through ssh: `cd nodebb && rhc ssh`):

``` sh
cat $OPENSHIFT_DATA_DIR/nodebb/config.json
```
