### ISSUE TITLE
Constant invalid-session errors

### ISSUE THREAD

**Issue by nsjohannes** [ahwayakchih/openshift-nodebb#23]
I've deployed a fresh install of NodeBB without any errors, except when I go onto the forum I get constant invalid-session errors and I'm not able to log into my account or do anything

**Comment by Benderwan** [comment]
As it is a fresh install it is probably not related to #17, could you provide more details about your version, database ? These errors are firing up in your web browser console ?

It might also be related to using custom domain names / ssl which is described [here](https://github.com/ahwayakchih/openshift-nodebb#custom-domain-name).

**Comment by nhlpl** [comment]
Please take a look here:
https://community.nodebb.org/post/52081

**Comment by ahwayakchih** [comment]
thanks @nhlpl.
