### ISSUE TITLE
Successfully deployed, but when login with administrator 

### ISSUE THREAD

**Issue by jianyunli** [ahwayakchih/openshift-nodebb#4]
directed me to a page

Forbidden

**Comment by nhlpl** [comment]
Could you please provide some more details about your issue? What you're trying to do and what is the URL?

You can login using data taken from step "8. That's it!". Just note them down and change after first successful login.

**Comment by jianyunli** [comment]
HI thanks for reply, I am trying to deploy nodebb following your instructions to openshift and it seems successful, but couldn't recognize the admin username/password provided after the Setup finished. New administrator has been created:

https://nodebb-greenbranch.rhcloud.com/login

I tried to register a new user, and it is also OK, but no emails received.

**Comment by jianyunli** [comment]
Sorry, it's my bad, in the CMD on windows, the letter small l looks like digit 1, after I typed in the correct password, and I can successfully login in as admin.

This is amazing, saving me lots of headache.

**Comment by ahwayakchih** [comment]
Thanks for letting us know :).
