### ISSUE TITLE
Redis version to low

### ISSUE THREAD

**Issue by PAEz** [ahwayakchih/openshift-nodebb#6]
The newer NodeBB needs redis 2.8.9 and above so the cart you list is to old.
This one works....
https://github.com/transformatordesign/openshift-redis-cart

Great thing youve done here, been having so many hassles getting nodebb to work.
All those notes you put in on updating and what not is just gravy, thanks!

**Comment by ahwayakchih** [comment]
Thanks for the info :)! I'm glad you found this project useful :).

Would you like to create pull request with changes needed? I quickly checked the cart you linked, and i'm not sure if it uses the same evironment variables as the cart i used. If they are different, we would have to change `app.js` file too.

**Comment by ahwayakchih** [comment]
Thanks @PAEz - i've tested installation and it seems to work, so i've updated README with new Redis cartrige.
