### ISSUE TITLE
NodeBB v0.8.x 

### ISSUE THREAD

**Issue by negati-ve** [ahwayakchih/openshift-nodebb#8]
# NodeBB v0.8.x on OpenShift.

following the steps here, just installed v0.8.1 .

The issues I encountered 
- The admin panel didn't load up any data on the UI (dashboard). 
- The categories section in the admin panel didn't show up at all. 
- Unable to create new posts. (error : you do not have enough privileges )
- Occasional, "not logged in" errors although user is logged in. 

Installation is located at: 
http://hackers.negative.co.in

**Comment by negati-ve** [comment]
seems like a sessions/cookie domain issue.

**Comment by ahwayakchih** [comment]
Hi,

Thanks for report.

Since your site is on custom domain, and accessing it through HTTPS warns about insecure site, my guess is that it may be caused by no-valid-SSL stuff.

Did you follow additional steps for setting up custom domain (https://github.com/ahwayakchih/openshift-nodebb#custom-domain-name)?

If so, which option did you try for no-SSL workaround?

**Comment by negati-ve** [comment]
both. 

'IO' cookie was set to the openshift domain and the 'express.sid' cookie was set to my custom domain. 
seems like these two have to be on the same domain for nodebb to function correctly. 

so,I unset OPENSHIFT_NODEBB_WS_USE_APP_DNS .

Happy to report that the installation seems pretty stable now. 
I think you can safetly update the readme to reflect that the guide has been tested with v0.8.x :+1:

**Comment by ahwayakchih** [comment]
Hmm... it worked ok when i last tested it with that option, but only that option (meaning, only one of the options was tested at a time, never both at the same time), but i did not test it with additional plugins.

Great to read that it works now :).

Thanks!

**update:** updated README with 0.8.x.

**Comment by Benderwan** [comment]
Having read that, I only have to say that it might work well at the beginning because you're still having cookies set from the Openshift domain and being used by the custom domain, while it might not work when having no cookies, you log in from the custom domain.

**Comment by negati-ve** [comment]
May I suggest you give it a run at my installation @ http://hackers.negative.co.in ?

Seems pretty stable.
If you can recreate a problem, let us know !

**Comment by Benderwan** [comment]
Your installation is fine as you are not using HTTPS thus every connection is handled through your main domain :smile:
